import fs from 'fs';
import xml2jsParser from 'xml2js-parser';
// import hexConverter from '../src/hexConverter';


const data = fs.readFileSync('./aepx/testProject.aepx');
const target = xml2jsParser.parseStringSync(data);
const item = target.AfterEffectsProject.Fold[0].Item[3];

// layers: Layr, SLay, CLay, SecL
console.dir(item.Layr.length);
console.dir(item.SLay.length);
console.dir(item.CLay.length);
console.dir(item.SecL.length);

// Ewst, fvdv, fiop, ftts, foac, fiac, fipc, fifl
console.dir(item.Ewst.length);
console.dir(item.fvdv.length);
console.dir(item.fiop.length);
console.dir(item.ftts.length);
console.dir(item.foac.length);
console.dir(item.fiac.length);
console.dir(item.fipc.length);
console.dir(item.fifl.length);

// console.dir(item);
/*
{ idta: [ { '$': [Object] } ],
  string: [ 'Test-Comp-Animated' ],
  cdta: [ { '$': [Object] } ],
  cdrp: [ { '$': [Object] } ],
  PRin: [ { prin: [Array], prda: [Array] } ],
  Layr:
   [ { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] },
     { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] },
     { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] },
     { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] } ],
  Ewst:
   [ { ewin: [Array], ewot: [Array] },
     { ewin: [Array], ewot: [Array] },
     { ewin: [Array], ewot: [Array] },
     { ewin: [Array], ewot: [Array] },
     '\n\t\t\t',
     '\n\t\t\t',
     '\n\t\t\t',
     '\n\t\t\t',
     '\n\t\t\t',
     '\n\t\t\t',
     '\n\t\t\t',
     '\n\t\t\t',
     '\n\t\t\t',
     '\n\t\t\t' ],
  fvdv:
   [ { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] } ],
  fiop:
   [ { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] } ],
  ftts:
   [ { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] } ],
  foac:
   [ { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] } ],
  fiac:
   [ { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] } ],
  fipc:
   [ { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] } ],
  fifl:
   [ { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] },
     { '$': [Object] } ],
  SLay:
   [ { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] },
     { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] },
     { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] },
     { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] },
     { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] },
     { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] } ],
  CLay:
   [ { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] },
     { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] },
     { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] } ],
  SecL:
   [ { ldta: [Array], string: [Array], tdgp: [Array], Gide: [Array] } ],
  Gide: [ { gdta: [Array], list: [Array] } ] }
*/
